### PR TITLE
Unify test syntax

### PR DESCRIPTION
**Pull request by Jacobkg**
Make all test files use the same syntax. This helps the test output appear in a single place instead of split up by file.

WIP - Seeing what Travis thinks for all ruby versions

### CODE REVIEW

**Comment by steveklabnik** [comment]
I wanted to get @shopify's commits in, and so this caused merge conflicts. Sorry about that!

**Comment by Jacobkg** [comment]
@steveklabnik If you like it, this is now ready to go

**Comment by steveklabnik** [comment]
Woot! Thanks!

**Comment by steveklabnik** [comment]
Sorry, I had to revert this PR because it made tests fail again: https://github.com/resque/resque/pull/1383

I cannot re-open it, mind sending in another one?

**Comment by Jacobkg** [comment]
Yeah, I'll send one along

**Pull request merged**
