### PR TITLE
Pagination improvements

### PR DESCRIPTION
**Pull request by josh-m-sharpe**
1) reverses order of pagination pages so that they increase
2) makes pages start with "1" instead of "0"
3) Adds a bit of style

Old:
78507041-d0f21500-774b-11ea-8a71-5f4dee6bbeee

New:

Screen Shot 2020-04-08 at 6 13 46 PM

### CODE REVIEW

**Comment by jsharpe-ctm** [comment]
@Shivang44 What are next steps to get a merge?

**Comment by Shivang44** [comment]
> @Shivang44 What are next steps to get a merge?

Not entirely sure. In the past I've seen @rafaelfranca merge PRs. Are you able to take a look at this?

**Comment by iloveitaly** [comment]
@josh-m-sharpe Thanks for the contribution! Great improvement over the existing pagination.

**Review by iloveitaly — APPROVED** [review]

**Comment by josh-m-sharpe** [comment]
@iloveitaly what are next steps here?  @Shivang44 "approved" this change over a year ago.  Is anyone merging things these days?

**Comment by iloveitaly** [comment]
I'm working with rafaelfranca to get some of these PRs merged in.

**Pull request merged**
