### PR TITLE
fall back to standard implementation of respond_to? for data store

### PR DESCRIPTION
**Pull request by m1lt0n**
As a good measure respond_to? could return whether the data store responds to a method of itself, too, as it could lead to bugs in code using the data store and relying on the default behaviour of respond_to?

I might contribute some really small things while familiarizing myself with the codebase of the project. Sorry for perhaps the multiple PRs.

### CODE REVIEW

**Comment by fw42** [comment]
I think you just pushed this same commit to https://github.com/resque/resque/pull/1494 as well.. That probably wasn't intended? Can you use separate branches?

**Comment by m1lt0n** [comment]
@fw42 Yes, you're right, sorry for that. Preparing a PR with a separate branch. You can close the other PR.

**Comment by fw42** [comment]
does this fix a particular problem that you ran into? or "just in case"?

**Comment by m1lt0n** [comment]
@fw42 Just in case. If it seems like overengineering, feel free to close it :)

**Pull request merged**
