### PR TITLE
Update Readme file with remove unwanted comma before and.

### PR DESCRIPTION
**Pull request by nikhilthombare**
Updated Readme document.

### CODE REVIEW

**Comment by chrisccerami** [comment]
Someone dislikes the Oxford comma 😉

**Comment by crazymykl** [comment]
Oxford Comma should be kept.

**Comment by nikhilthombare** [comment]
Ohhh got it..

**Comment by chrisccerami** [comment]
@nikhilthombare in all seriousness, the use of the Oxford comma is a matter of opinion. While there might be some who find the Readme clearer without them, I could easily see someone opening a new PR in a few months to add "missing" commas, just like yours removes "unwanted" commas. While I'm in favor of improving documentation whenever possible, I think minor stylistic changes like this only manage to cause more change without actually making significant differences.

Because of this I'm going to close this PR, but I hope you'll feel free to contribute to our documentation in the future.

**Pull request closed without merging**
