### PR TITLE
Performance fixes and metrics

### PR DESCRIPTION
**Pull request by fw42**
This is essentially https://github.com/Shopify/resque/pull/9 (and https://github.com/Shopify/resque/pull/10), but against upstream/1-x-stable. (Also polished a few rough edges.)

@steveklabnik @sirupsen @dylanahsmith

### CODE REVIEW

**Comment by fw42** [comment]
Tests failed because I'm using keyword arguments. Do you want 1-x-stable to be Ruby 1.9 compatible?

**Comment by Sirupsen** [comment]
For context, we needed these calls for querying Resque across datacenters where we can't afford the otherwise 10s of roundtrips. We've been running this in production for ~6 months for monitoring purposes.

**Comment by steveklabnik** [comment]
> Do you want 1-x-stable to be Ruby 1.9 compatible?

We need to be 1.8 compatible, yes. If there's something super, super onerous that makes sense to drop 1.8, then I will, but kwargs aren't enough to justify it :)

**Comment by steveklabnik** [comment]
This looks great! Let's get Travis green and then :shipit:

**Comment by fw42** [comment]
> We need to be 1.8 compatible, yes

Just out of curiosity: Why? That's ancient :)

**Comment by fw42** [comment]
Tests are passing now :green_apple:

**Comment by steveklabnik** [comment]
@fw42 it is, but without knowing any kind of metrics, I can't know how many people are still relying on it, even though it's EOL :( Maybe _this_ would be a good motivation for a Resque 2.0, rather than a full re-write.

Anyway, woo! Green! Let's go!

**Pull request merged**
