### PR TITLE
Revert #461/PR #967 to restore proper daemonization behaviour when BACKGROUND=1.  Fixes #1122.

### LINKED ISSUE #1122: Launching workers with BACKGROUND=yes hangs with 1.25.0
I upgraded from 1.24.1 to 1.25.0 and now my deploys hang when trying to start worker processes via rake with the BACKGROUND=yes flag.  I assume this is related to #895.  The command I'm using looks like this:

bundle exec rake BACKGROUND=yes INTERVAL=1 PIDFILE=/tmp/resque1.production.pid QUEUES=ts_delta RAILS_ENV=production environment resque:work

### PR DESCRIPTION
**Pull request by rbroemeling**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Hey there! It's been a while, sorry about that.

@hoffmanc and I are going to be working on Resque again, but this PR needs a rebase. If you get the chance, would you mind

1. reabasing, if you're up for it
2. if you're not up for it, that's cool, just let us know so we can investigate

Thanks! / sorry :frowning:

**Comment by steveklabnik** [comment]
I'm going to give this a close, then. Sorry again :(

**Comment by rbroemeling** [comment]
@steveklabnik I missed this update -- it has been a _really_ long time. What exactly do you need done for this? Issue #1122 is still very real, although it hasn't bitten us in a long time since we've worked around it in our own fork.

**Comment by steveklabnik** [comment]
Yeah, it has :( It needs a rebase.

> we've worked around it in our own fork.

In general, I would love to do what it takes to get you back on main Resque. I'm planning on doing some work and cutting a new release, so if you're interested, we could get any patches you have applied.

**Comment by rbroemeling** [comment]
@steveklabnik The change was a very small one -- just to revert the erroneous forking behaviour that was implemented in #461/PR #967. The code has changed so drastically since I did the original PR that it made more sense to reimplement the change than it did to try and rebase it. I've opened PR #1371, which is the re-implementation of the change on the new code.

**Comment by steveklabnik** [comment]
Great! I've merged it. Thanks again.

I'm hoping to get the new release out soonish, but won't promise anything sooner than a month. I'm still picking back up development, and it's 100% on my own time, soooo.

**Pull request closed without merging**
