### PR TITLE
Remove support for Rubies < 2.0.0

### PR DESCRIPTION
**Pull request by chrisccerami**
With this PR, I'm proposing that we officially remove support for any Rubies older than 2.1.10. My reasoning for this is that while legacy support has and will be an important goal for Resque, we simply can't support every Ruby throughout history.

Ruby 1.8.7 was released in 2008 and End-of-Lifed in 2013.

Ruby 1.9.3 was released in 2011 and EOLed in 2014.

Even 2.0.0 was released in 2013 and was EOLed at the end of 2015.

While Ruby 2.1.10 will be EOLed soon, I think that for now it is the most reasonable minimum Ruby version for any further releases of Resque. I hope to hear from the rest of the Resque team and those using Resque to gain some sort of consensus on this point.

### CODE REVIEW

**Comment by chrisccerami** [comment]
Related to #1526

**Comment by steveklabnik** [comment]
Not that I have a ton of weight in this, but I feel like dropping support for these rubies is worth a 2.0 release. Something to consider; please don't consider this opinion blocking.

**Comment by chrisccerami** [comment]
@steveklabnik I don't disagree with you. I think it could be seen as a breaking change.

**Comment by oss92** [comment]
You will need to remove 
```
if RUBY_VERSION <= '1.9'
  require 'resque/vendor/utf8_util/utf8_util_18'
else
  require 'resque/vendor/utf8_util/utf8_util_19'
end
```

and remove `resque/vendor/utf8_util/utf8_util_18` and `resque/vendor/utf8_util/utf8_util_19` after copying the `clean!` method from the latter.

**Comment by pboling** [comment]
Dropping support for any Ruby version is one of the best reasons for a major version bump.  See SemVer 2.0#8 -
> 8. Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

Source: http://semver.org/

Regardless of whether or not this project follows all of the principles of SemVer or not, there are good reasons for this rule.

**Comment by chrisccerami** [comment]
Sure, I think we all agree with that.

**Comment by chrisccerami** [comment]
I think we've collected enough feedback to say that people are probably comfortable with removing support for < 2.0.0, so I'm going to merge this into master. I'm not going to release it right away, as this will constitute a 2.x version of Resque, and we may want to make other changes at the same time.

**Pull request merged**
