### PR TITLE
Fail rake rescue:workers if COUNT is not set

### PR DESCRIPTION
**Pull request by Jacobkg**
2nd of 2 PRs to address #1253 

Added a check that the COUNT environment variable is set to a number greater than 0 with an appropriate error message.

Refactored the test file a bit in order to support testing multiple rake tasks, and also switched it to using the `describe` syntax of minitest. Finally borrowed some code from Rails to silence stderr messages so as to not pollute the test output.

### CODE REVIEW

**Comment by steveklabnik** [comment]
It looks like `IO::NULL` wasn't around in 1.8.

**Comment by Jacobkg** [comment]
Yeah, just noticed that. Getting a 1.8.7 environement up and running so I can fix.

**Comment by Jacobkg** [comment]
@steveklabnik I realized that there already was an error output suppresion method I could call from `test_helper.rb` so switched to that and travis is now green

**Comment by steveklabnik** [comment]
Thanks!

**Pull request merged**
