### PR TITLE
Ensure Resque travis builds have latest version of bundler

### PR DESCRIPTION
**Pull request by RochesterinNYC**
- Prevents following error: `NoMethodError: undefined method 'spec' for nil:NilClass`

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
Saw the error (`NoMethodError: undefined method 'spec' for nil:NilClass`) in one of the builds for #1363.

Refer to PR/issue here: thoughtbot/factory_girl#846

**Comment by RochesterinNYC** [comment]
Hm, Airbrake is breaking in the builds for later versions of Ruby (`>= 1.9.3`)

**Comment by RochesterinNYC** [comment]
@steveklabnik Seems like Airbrake migrated from version 4 to 5 for latest release and this is the cause? Especially seeing as how the Gemfiles for `1.8.7` and `1.9.2` are locked at `4.3.2` and `4.3.3.` respectively.

https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#general-changes

I can open another PR investigating how to migrate appropriately if needed. We can lock the version in at `4.3.4` in the meantime if we want to amend these errors for builds.

**Comment by steveklabnik** [comment]
Yeah, this seems ifne. I think that locking them in this way makes sense.

**Pull request merged**
