### PR TITLE
Issue 1230/multi failuire backend regression

### PR DESCRIPTION
**Pull request by irenemachine**
Fixes a few bugs around multi failure queue functionality:

Re-queueing/deleting a failed job uses the wrong index and wrong queue.
Failure overview page queue links broken.
Re-queueing/clearing all failed jobs doesn't work for all failure queues, only the failed queue.

### CODE REVIEW

**Comment by omarqureshi** [comment]
Is it worth adding some tests around requeues? I'm happy to add some

**Comment by steveklabnik** [comment]
What ended up happening with this PR? It looks like it's to another branch, not an actual release?

**Comment by omarqureshi** [comment]
I've been using it on a fork, it does look ok.

**Comment by steveklabnik** [comment]
Yeah, I guess it's the 

> into resque:issue-1230/multi-failuire-backend-regression

that I'm confused about. This isn't going into the actual code but some other branch?

**Comment by omarqureshi** [comment]
It's not named great for sure - but, does apply to master and doesn't need anything from that PR/issue

**Comment by omarqureshi** [comment]
I'm not at my desk, but I think 1230 was the initial complaint of multiple failure queues not working

**Comment by steveklabnik** [comment]
Ah, so master isn't being developed anymore, so maybe this should just be closed?

**Comment by omarqureshi** [comment]
I dunno. Having multiple failure queues is pretty useful. Is that a feature for resque 2? If not can we get it in? It's pretty important. I don't mind doing the work to get it in.

**Comment by steveklabnik** [comment]
Resque 2 is entirely cancelled.

**Comment by omarqureshi** [comment]
Ah. Was master resque 2? This merged into whatever the working branch was for the 1.x resque.

**Comment by steveklabnik** [comment]
Yeah, master was going to be 2, and was a total redux. So that might be the miscommunication, if this is targetted at 1-x, then it should still be good to go in some fashion.

**Comment by steveklabnik** [comment]
I'm going to merge this into that branch, and then submit a new PR with that branch to 1-x-stable. Thakns!

**Pull request merged**
