### PR TITLE
fix Resque::Failure::Redis#each id assign when reversed order

### PR DESCRIPTION
**Pull request by Adrian2112**
`resque-web` on the failure tab the job ids in the queue where miscalculated and the jobs where not correctly paged 
`Resque v1.25.2`

This fix issue #1172

### CODE REVIEW

**Comment by steveklabnik** [comment]
Hey there! It's been a while, sorry about that.

@hoffmanc and I are going to be working on Resque again, but this PR needs a rebase. If you get the chance, would you mind

1. reabasing, if you're up for it
2. if you're not up for it, that's cool, just let us know so we can investigate

Thanks! / sorry :frowning:

**Comment by lukeasrodgers** [comment]
@steveklabnik I had been talking with @yaauie about addressing the issue, but if others are willing to provide a fix, I'd be happy to test it out. As mentioned above, I believe there are a couple issues with this PR. I think the ideal fix would address both the negative/incorrect failure indexing, and also the counter-intuitive failure ordering, introduced here: https://github.com/resque/resque/commit/10912efdcec91de7486e273f203c884db5f523f8

**Comment by steveklabnik** [comment]
I would still like to get everyone back on master for the next release. I've been merging some stuff related to failure counts, maybe this is okay now? Anyway, this still needs a rebase too, maybe doing so will let us evaluate the failures properly.

**Comment by lukeasrodgers** [comment]
@steveklabnik I will try out resque master with our app, and see if the failure count issues are resolved/improved, probably won't get around to it till next week though. Thanks for your efforts on this.

**Comment by steveklabnik** [comment]
Thanks! A small note: you should try `1-x-stable`, not `master`. I haven't switched it over yet, iirc.

**Comment by lukeasrodgers** [comment]
@steveklabnik I tried out 1-x-stable, the UI now appears to correctly map failures to their IDs, so far, though there appears to be a slightly related regression, as mentioned here: https://github.com/resque/resque/pull/1374.

Also, the pagination UI is still highly counterintuitive, as per above. See attached for an example. 
screen shot 2016-01-19 at 12 31 48 pm

Additionally, I think changing the sort order (currently not possible via the UI, but still semi-supported by adding `order=asc` to the querystring) is counterintuitive. If I change from the default "desc" to "asc", each page is reordered, but the overall ordering is unchanged (i.e. page 0 is still farther to the right, and lists the same set of failures, 0-19). 

I would be happy to work on this, though probably wouldn't be able to complete it for a couple weeks due to work/family commitments.

**Comment by steveklabnik** [comment]
Adding to the milestone so we can make sure to track the regression.

**Comment by steveklabnik** [comment]
Okay, this regression is the final blocker for 1.26.0. Gotta figure it out.

**Comment by steveklabnik** [comment]
I have submitted https://github.com/resque/resque/pull/1427 to fix the regression. 

In the meantime, I _think_ that this PR's issue was fixed with other means, so let's track that issue there, and close this  PR. Thanks all!

**Pull request closed without merging**
