### PR TITLE
remove warnings from test output

### PR DESCRIPTION
**Pull request by hoffmanc**
this PR cleans up test output.

### CODE REVIEW

**Comment by yaauie** [comment]
I'll try to have a commit-by-commit look at this over the weekend; my initial impression is that the cleanup in here could be very useful, but since there's a lot going on I'll need a better look before merging.

Thanks!

**Comment by hoffmanc** [comment]
Thanks for looking at it!

**Comment by hoffmanc** [comment]
I'm happy to reorganize / remove commits as well, if something seems unnecessary or not clear.

**Comment by hoffmanc** [comment]
@yaauie any luck looking over these commits?

**Comment by yaauie** [comment]
No luck yet; I had a busy weekend & started off the week sick. Message is
starred in my inbox & I hope to get to it soon.

-R

**Comment by hoffmanc** [comment]
Okay, thanks for the update.

**Comment by hoffmanc** [comment]
@yaauie Is there someone else I can reach out to that would be able to accept/reject this pull request?

**Comment by hoffmanc** [comment]
Can someone look over this over the weekend, please?  I really don't think it would take more than 30 minutes to review these commits.  Thanks in advance!

**Comment by hoffmanc** [comment]
@yaauie any luck looking at this PR?  Thanks!

**Comment by steveklabnik** [comment]
Looks great, thanks!

**Comment by hoffmanc** [comment]
Thanks @steveklabnik !

**Pull request merged**
