### PR TITLE
notify_or_ignore is gone in v5

### PR DESCRIPTION
**Pull request by orenmazor**
Updated my airbrake earlier this week and my jobs all immediately started failing due to this change: https://github.com/airbrake/airbrake/blob/23457a14144013959ffc4f54683238929e30f908/docs/Migration_guide_from_v4_to_v5.md#notify-or-ignore

### CODE REVIEW

**Comment by crazymykl** [comment]
Please fix the test failure on 1.8.7.

**Comment by orenmazor** [comment]
@crazymykl donezo :+1:

**Comment by chrisccerami** [comment]
I think there is a plan to remove Airbrake from Resque itself and instead use the separate gem. I'm not entirely sure what the status of that work is, but I assume this change would be compatible? @orenmazor

**Comment by steveklabnik** [comment]
It's true, but that work hasn't been done, so it's useful to merge in the meantime. Thanks @orenmazor !

**Comment by chrisccerami** [comment]
I believe this fixes #1428, right @steveklabnik?

**Pull request merged**
