### PR TITLE
Add graceful_term option so TERM works like QUIT (for 1-x-stable)

### PR DESCRIPTION
**Pull request by ktheory**
If Worker#graceful_term is enabled, SIGTERM waits for a job to complete
before exiting (just like SIGQUIT).

Worker#graceful_term defaults to ENV['GRACEFUL_TERM'].

This makes it possible to use resque with runit/daemontools without
resorting to a wrapper script.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Hey there! It's been a while, sorry about that.

@hoffmanc and I are going to be working on Resque again, but this PR needs a rebase. If you get the chance, would you mind

1. reabasing, if you're up for it
2. if you're not up for it, that's cool, just let us know so we can investigate

Thanks! / sorry :frowning:

**Comment by ktheory** [comment]
:wave: Hi @steveklabnik: just rebased & force-pushed to my fork.

**Comment by steveklabnik** [comment]
Looks like 1.8.7 is failing due to using 1.9 hash syntax, mind bringing the rocket back please?

**Comment by hoffmanc** [comment]
@steveklabnik I'm on it - it is a problem with airbrake

**Comment by steveklabnik** [comment]
I think the PR i just merged may fix the error, restarting travis

**Comment by steveklabnik** [comment]
Thanks so much! merging.

**Comment by nbulaj** [comment]
I'm wondering why Resque doesn't have any place where this feature described (like README or Wiki)? Because for now everybody seems to use https://github.com/iloveitaly/resque-heroku-signals

Would you like me to propose a PR to add it? @jeremy

**Pull request merged**
