### PR TITLE
Enable workers to restart when its job fails and on_failure hooks fail

### PR DESCRIPTION
**Pull request by RochesterinNYC**
* Add helpful log message for failures during on_failure hooks

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
Addresses #1353

**Comment by steveklabnik** [comment]
This has a merge conflict, would you mind rebasing please? Sorry for the delay in reviewing.

**Comment by RochesterinNYC** [comment]
S'all good! Rebased.

**Comment by steveklabnik** [comment]
Thanks so much!

**Pull request merged**
