### PR TITLE
Drop 1.8.7 and 1.9.3 from .travis.yml

### PR DESCRIPTION
**Pull request by sonots**
Ruby 1.8.7 and 1.9.3 are EOL. Why don't you drop 1.8.7 and 1.9.3 from .travis.yml?

### CODE REVIEW

**Comment by steveklabnik** [comment]
Even though they are EOL, they are used by a bunch of people, so we have still supported them. It's arguably a semver-breaking change. See http://resque.github.io/2016/03/10/resque-1.26.0-released.html for more.

That said, I don't really do much work anymore, so if the other maintainers wish to change this, well, that's up to them.

**Comment by chrisccerami** [comment]
I'd be very uncomfortable dropping support for Ruby < 2 without a major version increase to Resque.

**Comment by fw42** [comment]
https://github.com/resque/resque/pull/1501 fixes the broken tests for Ruby 1.8 and 1.9 so I'm gonna close this for now

**Comment by sonots** [comment]
Understand, thank you.

**Pull request closed without merging**
